/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameAutor.java
 *
 * Created on 2/Dez/2010, 15:50:20
 */

package javaapplication1;


import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Milton
 */
public class frameAutor extends javax.swing.JFrame {

    String autor = "";
    Nucleo nucleo;

    public frameAutor(Nucleo nuc){
        nucleo = nuc;
        initComponents();
        btnApagar.setVisible(false);
        btnGuardar.setText("Adicionar");
        lblAutor.setVisible(false);
        try {
            this.actualizarComboPais();
        } catch (Exception ex) {
            Logger.getLogger(frameAutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /** Creates new form frameAutor */
    public frameAutor(String autor, Nucleo nuc) throws Exception {
        nucleo = nuc;
        initComponents();
        this.autor = autor;
        carregarDados();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        txtPnome = new javax.swing.JTextField();
        dDia = new javax.swing.JTextField();
        dMes = new javax.swing.JTextField();
        dAno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtpais = new javax.swing.JTextField();
        combopais = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel3.setText("Código");

        lblAutor.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Autor");

        jLabel4.setText("Nome");

        jLabel6.setText("Data Nascimento");

        txtcod.setEditable(false);

        jLabel7.setText("País");

        txtpais.setEditable(false);

        combopais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "País" }));
        combopais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combopaisItemStateChanged(evt);
            }
        });

        jButton8.setText("Fechar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuardarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnApagar)
                        .addGap(6, 6, 6)
                        .addComponent(btnGuardar)
                        .addGap(6, 6, 6)
                        .addComponent(jButton8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPnome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dDia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(dMes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(dAno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtpais, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(combopais, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblAutor))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(txtPnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addComponent(dMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(txtpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(combopais, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApagar)
                    .addComponent(btnGuardar)
                    .addComponent(jButton8))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-415)/2, (screenSize.height-278)/2, 415, 278);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        this.dispose();
        nucleo.setEnab(true);
}//GEN-LAST:event_jButton8MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

}//GEN-LAST:event_jButton8ActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        if(btnApagar.getText().equals("Ativar")){
            try {
                nucleo.ativarAutor(txtcod.getText());
                JOptionPane.showMessageDialog(null, "Autor reativo com sucesso!");
                this.dispose();
                nucleo.setEnab(true);
                return;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        GregorianCalendar dateA = new GregorianCalendar();

        String data = dateA.get(Calendar.YEAR) + "." + dateA.get(Calendar.MONTH)+1 + "." + dateA.get(Calendar.DAY_OF_MONTH);
        
        try {
            nucleo.apagarAutor(txtcod.getText(), data);
            // TODO add your handling code here:
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
            return;
        }
        JOptionPane.showMessageDialog(null,"Autor apagado com sucesso!");
        this.dispose();
        nucleo.setEnab(true);        // TODO add your handling code here:
}//GEN-LAST:event_btnApagarActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        if(btnGuardar.getText().equals("Guardar")) try {
            update();
        nucleo.setEnab(true);
        } catch (Exception ex) {
            //Logger.getLogger(frameAutor.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
            return;
        }
        else try {
            gravar();
        nucleo.setEnab(true);
        } catch (Exception ex) {
            //Logger.getLogger(frameAutor.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null,"Erro a gravar, dados inválidos!");
            JOptionPane.showMessageDialog(null,ex);
            return;
        }
        JOptionPane.showMessageDialog(null,"Operação efectuada com sucesso!");
        this.dispose();
        nucleo.setEnab(true);
}//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyPressed

}//GEN-LAST:event_btnGuardarKeyPressed

    private void combopaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combopaisItemStateChanged
        txtpais.setText(combopais.getSelectedItem().toString());        // TODO add your handling code here:
    }//GEN-LAST:event_combopaisItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
           nucleo.setEnab(true);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    public void carregarDados()throws Exception{
        ResultSet autors = null;
        autors = nucleo.getAuthor(autor);
        while(autors.next()){
            lblAutor.setText(autors.getString(2));
            txtcod.setText(autors.getString(1));
            txtPnome.setText(autors.getString(2));
            if(autors.getString(3)!=null){
            dAno.setText(autors.getString(3).substring(0, 4));
            dMes.setText(autors.getString(3).substring(5, 7));
            dDia.setText(autors.getString(3).substring(8, 10));
            }
            if(autors.getString(4)!=null) {
                ResultSet aux = nucleo.getCountry(autors.getString(4));
                while (aux.next()){
                    txtpais.setText(aux.getString(2));
                }
                aux.close();
            }
            
        }
        autors.close();
        actualizarComboPais();


    }

    private void actualizarComboPais() throws Exception{
        ResultSet pais = nucleo.ListarPais();
        while(pais.next()){
            if(pais.getString(3)==null)combopais.addItem(pais.getString(2));
        }
        pais.close();
    }

    public void gravar() throws Exception {
        String nome1 = txtPnome.getText();
        String data = dAno.getText() + "." + dMes.getText() + "." + dDia.getText();
        String pais = verPais(txtpais.getText());
        nucleo.createAuthor(nome1, data, pais);
    }

    public void update() throws Exception {
        String cod = txtcod.getText();
        String nome1 = txtPnome.getText();
        String data = dAno.getText() + "." + dMes.getText() + "." + dDia.getText();
        String pais = verPais(txtpais.getText());
        nucleo.updateAuthor(cod, nome1, data, pais);
    }

    public String verPais(String nome)throws Exception{
        String res = "";
        ResultSet pais = nucleo.ListarPais();
        while(pais.next() && res.equals("")){
            if (pais.getString(2).equals(nome)) res = pais.getString(1);
        }
        pais.close();
        return res;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameAutor(new Nucleo()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox combopais;
    private javax.swing.JTextField dAno;
    private javax.swing.JTextField dDia;
    private javax.swing.JTextField dMes;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JTextField txtPnome;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtpais;
    // End of variables declaration//GEN-END:variables

}
