/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameDoc.java
 *
 * Created on 2/Dez/2010, 15:47:10
 */

package javaapplication1;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Milton
 */

/******Falta a especificaçao a beira do tema*******/
public class frameDoc extends javax.swing.JFrame {
   
    String doc = "";
    Nucleo nucleo;
    /** Creates new form frameDoc */
    public frameDoc(String doc, Nucleo nuc) throws Exception{
        
        initComponents();    
        nucleo=nuc;
        this.doc = doc;
        carregarDados();

       
    }

    public frameDoc(Nucleo nuc){
        nucleo=nuc;
        initComponents();
        jButton5.setText("Adicionar");
        labelnome.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void carregarDados()throws Exception{
        ResultSet docs = null;
        docs = nucleo.getDocInfo(doc);

        
        while(docs.next()){
            labelnome.setText(docs.getString(2));
            txtcod.setText(docs.getString(1));
            txtname.setText(docs.getString(2));
            txtdescr.setText(docs.getString(3));
            if(docs.getString(6)!=null){
            dAno.setText(docs.getString(6).substring(0, 4));
            dMes.setText(docs.getString(6).substring(5, 7));
            dDia.setText(docs.getString(6).substring(8, 10));
            }
            txttema.setText(docs.getString(13));
            txtuniv.setText(docs.getString(15));
            txtespec.setText(docs.getString(14));
            txtautor.setText(docs.getString(12));
            txttipo.setText(docs.getString(11));
            txtuser.setText(docs.getString(8));
        }
        docs.close();
        actualizarComboAutor();
        actualizarComboTema();
        actualizarComboType();
        actualizarComboUniv();
        actualizarComboEspec();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        labelnome = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txttipo = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        comboautor = new javax.swing.JComboBox();
        combouniv = new javax.swing.JComboBox();
        txtuniv = new javax.swing.JTextField();
        txtautor = new javax.swing.JTextField();
        txttema = new javax.swing.JTextField();
        comboespec = new javax.swing.JComboBox();
        txtespec = new javax.swing.JTextField();
        txtcod = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        combotema = new javax.swing.JComboBox();
        dAno = new javax.swing.JTextField();
        dMes = new javax.swing.JTextField();
        dDia = new javax.swing.JTextField();
        txtdescr = new java.awt.TextArea();
        combotipo = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel12.setText("Documento");

        labelnome.setText("jLabel2");

        jButton5.setText("Guardar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });

        jButton8.setText("Fechar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        txttipo.setEditable(false);
        txttipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipoActionPerformed(evt);
            }
        });

        txtuser.setEditable(false);

        comboautor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Autor" }));
        comboautor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboautorItemStateChanged(evt);
            }
        });

        combouniv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Univ" }));
        combouniv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combounivItemStateChanged(evt);
            }
        });

        txtuniv.setEditable(false);

        txtautor.setEditable(false);
        txtautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtautorActionPerformed(evt);
            }
        });

        txttema.setEditable(false);

        comboespec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Especifico" }));
        comboespec.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboespecItemStateChanged(evt);
            }
        });

        txtespec.setEditable(false);

        txtcod.setEditable(false);

        combotema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tema" }));
        combotema.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combotemaItemStateChanged(evt);
            }
        });

        combotipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo" }));
        combotipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combotipoItemStateChanged(evt);
            }
        });

        jLabel14.setText("Código");

        jLabel15.setText("Nome");

        jLabel19.setText("Descrição");

        jLabel18.setText("Data");

        jLabel20.setText("Universidade");

        jLabel17.setText("Tema");

        jLabel23.setText("Especifico");

        jLabel21.setText("Autor");

        jLabel16.setText("Tipo");

        jLabel22.setText("Utilizador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21)
                    .addComponent(jLabel17)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdescr, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dMes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(dDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(dAno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtuniv, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combouniv, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txttema, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combotema, 0, 99, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtespec, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboespec, 0, 99, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtautor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboautor, 0, 99, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combotipo, 0, 99, Short.MAX_VALUE))
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtdescr, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))
                            .addComponent(dDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtuniv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combouniv, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combotema, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtespec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addComponent(comboespec, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addComponent(comboautor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(labelnome, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(labelnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton5))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-475)/2, (screenSize.height-495)/2, 475, 495);
    }// </editor-fold>//GEN-END:initComponents

    public void guardar() throws Exception{
        String nome = txtname.getText();
        String tipo = verTipo(txttipo.getText());
        String descr = txtdescr.getText();
        String data = dAno.getText() + "." + dMes.getText() + "." + dDia.getText();
        String tema = verTema(txttema.getText());
        String espec = verEspec(txtespec.getText());
        String univ = verUniv(txtuniv.getText());
        String autor = verAutor(txtautor.getText());
        String user = txtuser.getText();
        nucleo.createDoc(nome, descr, data, tema, espec, univ, autor, tipo, user);
        JOptionPane.showMessageDialog(null, "Documento guardado com sucesso!");
        this.dispose();
    }

    public void update() throws Exception{
        String cod = txtcod.getText();
        String nome = txtname.getText();
        String tipo = verTipo(txttipo.getText());
        String descr = txtdescr.getText();
        String data = dAno.getText() + "." + dMes.getText() + "." + dDia.getText();
        String tema = verTema(txttema.getText());
        String espec = verEspec(txtespec.getText());
        String univ = verUniv(txtuniv.getText());
        String autor = verAutor(txtautor.getText());
        String user = txtuser.getText();
        nucleo.updateDoc(cod, nome, descr, data, tema, espec, univ, autor, tipo, user);
        JOptionPane.showMessageDialog(null, "Documento atualizado com sucesso!");
        this.dispose();
    }

    public String verTipo(String nome)throws Exception{
        String res = "null";
        ResultSet tipos = nucleo.listarTypes();
        while(tipos.next() && res.equals("null")){
            if (tipos.getString(2).equals(nome)) res = tipos.getString(1);
        }
        tipos.close();
        return res;
    }

    public String verTema(String nome)throws Exception{
        String res = "null";
        ResultSet temas = nucleo.listarArea();
        while(temas.next() && res.equals("null")){
            if (temas.getString(2).equals(nome)) res = temas.getString(1);
        }
        temas.close();
        return res;
    }

    public String verEspec(String nome)throws Exception{
        String res = "null";
        ResultSet especs = nucleo.listarSpec();
        while(especs.next() && res.equals("null")){
            if (especs.getString(2).equals(nome)) res = especs.getString(1);
        }
        especs.close();
        return res;
    }

    public String verUniv(String nome)throws Exception{
        String res = "null";
        ResultSet univs = nucleo.listarUniv();
        while(univs.next() && res.equals("null")){
            if (univs.getString(2).equals(nome)) res = univs.getString(1);
        }
        univs.close();
        return res;
    }

    public String verAutor(String nome)throws Exception{
        String res = "null";
        ResultSet autors = nucleo.listarAutores();
        while(autors.next() && res.equals("null")){
            if (autors.getString(2).equals(nome)) res = autors.getString(1);
        }
        autors.close();
        return res;
    }

    public String verUser(String nome)throws Exception{
        String res = "null";
        ResultSet users = nucleo.listarUsers();
        while(users.next() && res.equals("null")){
            if (users.getString(2).equals(nome)) res = users.getString(1);
        }
        users.close();
        return res;
    }

    private void txttipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipoActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        dispose();
        nucleo.setEnab(true);
}//GEN-LAST:event_jButton8MouseClicked

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if(jButton5.getText().equals("Guardar")) try {
            update();
            nucleo.setEnab(true);
        } catch (Exception ex) {
            Logger.getLogger(frameDoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        else try {
            guardar();
            nucleo.setEnab(true);
        } catch (Exception ex) {
            Logger.getLogger(frameDoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void combounivItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combounivItemStateChanged
        String t = combouniv.getSelectedItem().toString();
        if(t.equals("Univ")) t = "";
        txtuniv.setText(t);
    }//GEN-LAST:event_combounivItemStateChanged

    private void combotemaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combotemaItemStateChanged
        String t = combotema.getSelectedItem().toString();
        if(t.equals("Tema")) t = "";
        txttema.setText(t);
    }//GEN-LAST:event_combotemaItemStateChanged

    private void comboespecItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboespecItemStateChanged
        String t = comboespec.getSelectedItem().toString();
        if(t.equals("Especifico")) t = "";
        txtespec.setText(t);
    }//GEN-LAST:event_comboespecItemStateChanged

    private void comboautorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboautorItemStateChanged
        String t = comboautor.getSelectedItem().toString();
        if(t.equals("Autor")) t = "";
        txtautor.setText(t);
    }//GEN-LAST:event_comboautorItemStateChanged

    private void combotipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combotipoItemStateChanged
        String t = combotipo.getSelectedItem().toString();
        if(t.equals("Tipo")) t = "";
        txttipo.setText(t);
    }//GEN-LAST:event_combotipoItemStateChanged

    private void txtautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtautorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtautorActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        nucleo.setEnab(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void actualizarComboTema() throws Exception{
        ResultSet temas = nucleo.listarArea();
        while(temas.next()){
            if(temas.getString(3)==null) combotema.addItem(temas.getString(2));
        }
        temas.close();
    }

    private void actualizarComboUniv() throws Exception{
        ResultSet univers = nucleo.listarUniv();
        while(univers.next()){
            if(univers.getString(4)==null) combouniv.addItem(univers.getString(2));
        }
        univers.close();

    }
    private void actualizarComboAutor() throws Exception{
        ResultSet author1 = nucleo.listarAutores();
        while(author1.next()){
            if (author1.getString(5)==null)comboautor.addItem(author1.getString(2));
        }
        author1.close();
    }

    private void actualizarComboType() throws Exception{
        ResultSet types = nucleo.listarTypes();
        while(types.next()){
            if(types.getString(3)==null) combotipo.addItem(types.getString(2));
        }
        types.close();
    }
    private void actualizarComboEspec() throws Exception{
        ResultSet especs = nucleo.listarSpec();
        while(especs.next()){
            if(especs.getString(4)==null) comboespec.addItem(especs.getString(2));
        }
        especs.close();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameDoc(new Nucleo()).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboautor;
    private javax.swing.JComboBox comboespec;
    private javax.swing.JComboBox combotema;
    private javax.swing.JComboBox combotipo;
    private javax.swing.JComboBox combouniv;
    private javax.swing.JTextField dAno;
    private javax.swing.JTextField dDia;
    private javax.swing.JTextField dMes;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelnome;
    private javax.swing.JTextField txtautor;
    private javax.swing.JTextField txtcod;
    private java.awt.TextArea txtdescr;
    private javax.swing.JTextField txtespec;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttema;
    private javax.swing.JTextField txttipo;
    private javax.swing.JTextField txtuniv;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

}
